<font face="arial, tahoma, verdana" size="1">
<h3><a name="2">Disclaimer</a> </h3>
<p><b><font size="2">1. Content</font></b> <br>
The author reserves the right not to be responsible for the topicality, correctness, 
completeness or quality of the information provided. Liability claims regarding 
damage caused by the use of any information provided, including any kind of information 
which is incomplete or incorrect,will therefore be rejected. <br>
All offers are not-binding and without obligation. Parts of the pages or the complete 
publication including all offers and information might be extended, changed or partly 
or completely deleted by the author without separate announcement. </p>
<p><b><font size="2">2. Referrals and links</font></b> <br>
The author is not responsible for any contents linked or referred to from his pages 
- unless he has full knowledge of illegal contents and would be able to prevent 
the visitors of his site fromviewing those pages. If any damage occurs by the use 
of information presented there, only the author of the respective pages might be 
liable, not the one who has linked to these pages. Furthermore the author is not 
liable for any postings or messages published by users of discussion boards, guestbooks 
or mailinglists provided on his page. </p>
<p><b><font size="2">3. Copyright</font></b> <br>
The author intended not to use any copyrighted material for the publication or, 
if not possible, to indicatethe copyright of the respective object. <br>
The copyright for any material created by the author is reserved. Any duplication 
or use of objects such as images, diagrams, sounds or texts in other electronic 
or printed publications is not permitted without the author&#39;s agreement. </p>
<p><b><font size="2">4. Privacy policy</font></b> <br>
If the opportunity for the input of personal or business data (email addresses, 
name, addresses) is given, the input of these data takes place voluntarily. The 
use and payment of all offered services are permitted - if and so far technically 
possible and reasonable - without specification of any personal data or under specification 
of anonymized data or an alias. The use of published postal addresses, telephone 
or fax numbers and email addresses for marketing purposes is prohibited, offenders 
sending unwanted spam messages will be punished. </p>
<p><b><font size="2">5. Legal validity of this disclaimer</font></b> <br>
This disclaimer is to be regarded as part of the internet publication which you 
were referred from. If sections or individual terms of this statement are not legal 
or correct, the content or validity of the other parts remain uninfluenced by this 
fact. <br>
&nbsp;</p>
</font>