<%@ Page Language="VB" Inherits="CompuMaster.camm.WebManager.Pages.Administration.UsersClone" %>

<%@ Register TagPrefix="camm" TagName="WebManager" Src="~/system/cammWebManager.ascx" %>
<camm:WebManager PageTitle="Administration - Clone user account" id="cammWebManager" SecurityObject="System - User Administration - Users" runat="server" />
<%@ Register TagPrefix="camm" TagName="WebManagerAdminBlockHeader" Src="adminblockheader.ascx" %>
<%@ Register TagPrefix="camm" TagName="WebManagerAdminBlockFooter" Src="adminblockfooter.ascx" %>
<%@ Register TagPrefix="camm" TagName="WebManagerAdminBlockContentLine" Src="adminblockcontentline.ascx" %>
<!--#include virtual="/sysdata/includes/standardtemplate_top_serverform.aspx"-->
<h3>
	<font face="Arial">Administration - Clone user account</font></h3>
<p>
    <asp:Label runat="server" id="lblStatusMsg" />
	<font face="Arial" size="2" color="red">
		<asp:label runat="server" id="lblErrMsg" />
		<asp:validationsummary id="ValidationSummary1" runat="server" headertext="Please solve the following issues to continue:" />
	</font>
</p>
<table cellspacing="0" cellpadding="0" bgcolor="#ffffff" border="0" bordercolor="#C1C1C1">
	<tbody style="font-size: small">
		<tr>
			<td valign="top">
				<table align="left" cellspacing="0" cellpadding="3" width="100%" height="550px" border="0" bordercolor="#FFFFFF">
					<tbody>
						<tr>
							<td bgcolor="#C1C1C1" colspan="2">
									<font face="Arial" size="2"><b>Source user login</b></font>
							</td>
							<td bgcolor="#C1C1C2">
									<font face="Arial" size="2"><b>Destination user login</b></font>
							</td>
						</tr>
						<tr>
							<td valign="Top" width="160">
									<font face="Arial" size="2">ID &nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:label runat="server" id="lbl_ID" />&nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:label runat="server" id="New_Field_ID" />&nbsp;</font>
							</td>
						</tr>
						<tr>
							<td valign="Top" width="160">
									<font face="Arial" size="2">Login <font color="#C1C1C1">*</font>&nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:label runat="server" id="lbl_LoginName" />
										&nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:textbox runat="server" width="200px" id="New_Field_LoginName" onfocus="this.select()" maxlength="20" />
										<asp:RequiredFieldValidator runat="server" controltovalidate="New_Field_LoginName" errormessage="Missinglogin name" text="*" />
										<asp:customvalidator runat="server" onservervalidate="ValidatorNewUserLoginName_ServerValidate" id="ValidatorNewUserLoginName" errormessage="Login name already exists" controltovalidate="New_Field_LoginName">*</asp:customvalidator>
									</font>
							</td>
						</tr>
						<tr>
							<td valign="Top" width="160">
									<font face="Arial" size="2">Password <font color="#C1C1C1">*</font>&nbsp;</font>
							</td>
							<td valign="Top" width="240">
								<font face="Arial" size="2">Autogenerated if empty</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:textbox runat="server" width="200px" textmode="Password" id="New_Field_Password" onfocus="this.select()" />
										&nbsp;</font>
							</td>
						</tr>
						<camm:WebManagerAdminBlockFooter runat="server" />
						<tr>
							<td bgcolor="#C1C1C1" colspan="3">
									<font face="Arial" size="2"><b>Personal data:</b></font>
							</td>
						</tr>
						<tr>
							<td valign="Top" width="160">
									<font face="Arial" size="2">Company <font color="#C1C1C1"></font>&nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:label width="200px" runat="server" id="lbl_Company" />&nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:textbox width="200px" runat="server" id="New_Field_Company" onfocus="this.select()" />
									</font>
							</td>
						</tr>
						<tr>
							<td valign="Top" width="160">
									<font face="Arial" size="2">
										<nobr>Gender <font color="#C1C1C1"> </font> &nbsp;</nobr>
									</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:label id="lblAnrede" runat="Server" style="width: 200px" size="1" />
									</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:dropdownlist id="cmbAnrede" runat="Server" style="width: 200px" size="1" />
									</font>
							</td>
						</tr>
						<tr>
							<td valign="Top" width="160">
									<font face="Arial" size="2">Academic Title (e. g. "Dr.")&nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:label width="200px" runat="server" id="lbl_Titel" />
										&nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:textbox width="200px" runat="server" maxlength="20" id="New_Field_Titel" onfocus="this.select()" />
										&nbsp;</font>
							</td>
						</tr>
						<tr>
							<td valign="Top" width="160">
									<font face="Arial" size="2">First name &nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:label width="200px" runat="server" id="lbl_Vorname" />
										&nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:textbox width="200px" runat="server" maxlength="30" id="New_Field_Vorname" onfocus="this.select()" />
									</font>
							</td>
						</tr>
						<tr>
							<td valign="Top" width="160">
									<font face="Arial" size="2">Last name &nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:label width="200px" runat="server" id="lbl_Nachname" />
										&nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:textbox width="200px" runat="server" maxlength="30" id="New_Field_Nachname" onfocus="this.select()" />
									</font>
							</td>
						</tr>
						<tr>
							<td valign="Top" width="160">
									<font face="Arial" size="2">Name addition &nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:label width="200px" runat="server" id="lbl_Namenszusatz" />
										&nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:textbox width="200px" runat="server" maxlength="20" id="New_Field_Namenszusatz" onfocus="this.select()" />
										&nbsp;</font>
							</td>
						</tr>
						<tr>
							<td valign="Top" width="160">
									<font face="Arial" size="2">e-mail <font color="#C1C1C1">*</font> &nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:label width="200px" runat="server" id="lbl_e_mail" />
										&nbsp;</font>
							</td>
							<td valign="Top" width="240">
									<font face="Arial" size="2">
										<asp:textbox width="200px" runat="server" maxlength="50" id="New_Field_e_mail" onfocus="this.select()" />
										<asp:RequiredFieldValidator runat="server" controltovalidate="New_Field_e_mail" errormessage="Missing email address" text="*" />
										<asp:regularexpressionvalidator runat="server" id="regularexpressionvalidatorEMail" controltovalidate="New_Field_e_mail" errormessage="The email address is not valid." text="*" validationexpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:regularexpressionvalidator>
										&nbsp;</font>
							</td>
						</tr>
						<tr>
							<td valign="Top" colspan="2">
							</td>
						</tr>
						<asp:panel id="PnlAddFlags" runat="server" />
						<tr>
							<td valign="Top" colspan="2">
							</td>
						</tr>
						<asp:panel runat="server" id="PnlGroupsInformation" />
						<tr>
							<td valign="Top" colspan="2">
							</td>
						</tr>
						<asp:panel id="PnlAuth" runat="server" />
					</tbody>
				</table>
			</td>
			<tr>
				<td valign="Top">
					&nbsp;
				</td>
				<td valign="Middle" align="Right">
					&nbsp;
				</td>
			</tr>
		<tr>
			<td valign="Top">
					<font face="Arial" size="2">
						<input type="text" style="display: none" />
						<asp:button runat="server" id="Button_Submit" text="Clone account" />
					</font>
			</td>
			<td valign="Middle" align="Right">
				<font face="Arial" size="2" color="#C1C1C1">* required fields</font>
			</td>
		</tr>
	</tbody>
</table>
<%@ Register TagPrefix="camm" TagName="WebManagerAdminMenu" Src="adminmenu.ascx" %>
<camm:WebManagerAdminMenu HRef="users.aspx" ID="cammWebManagerAdminMenu" runat="server" />
<!--#include virtual="/sysdata/includes/standardtemplate_bottom_serverform.aspx"-->
