'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete/Deactivate this market ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_DeactivateDeleteMarket() As String
            Get
                Return ResourceManager.GetString("Label_DeactivateDeleteMarket", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Insert document ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_InsertDocument() As String
            Get
                Return ResourceManager.GetString("Label_InsertDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Insert image ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_InsertImage() As String
            Get
                Return ResourceManager.GetString("Label_InsertImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you want to close this site without saving your changes? ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_JSString_AreYouSureToClose() As String
            Get
                Return ResourceManager.GetString("Label_JSString_AreYouSureToClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you want to leave? All your changes will be lost! ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_JSString_AreYouSureToLeave() As String
            Get
                Return ResourceManager.GetString("Label_JSString_AreYouSureToLeave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New Version ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_NewVersion() As String
            Get
                Return ResourceManager.GetString("Label_NewVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No versions available ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_NoVersionsAvailable() As String
            Get
                Return ResourceManager.GetString("Label_NoVersionsAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Neutral / All ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_Option_NeutralMarket() As String
            Get
                Return ResourceManager.GetString("Label_Option_NeutralMarket", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die (new) ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_Option_New() As String
            Get
                Return ResourceManager.GetString("Label_Option_New", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die (no release) ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_Option_NoRelease() As String
            Get
                Return ResourceManager.GetString("Label_Option_NoRelease", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Preview ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_Preview() As String
            Get
                Return ResourceManager.GetString("Label_Preview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_Save() As String
            Get
                Return ResourceManager.GetString("Label_Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save &amp; Activate ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_SaveNActivate() As String
            Get
                Return ResourceManager.GetString("Label_SaveNActivate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save &amp; Activate all languages/markets of this version ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_SaveNActivate_Tooltip() As String
            Get
                Return ResourceManager.GetString("Label_SaveNActivate_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  (inactive) ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_Suffix_Inactive() As String
            Get
                Return ResourceManager.GetString("Label_Suffix_Inactive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die With changes ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_WithChanges() As String
            Get
                Return ResourceManager.GetString("Label_WithChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Without changes since version  ähnelt.
        '''</summary>
        Friend ReadOnly Property Label_WithoutChangesSinceVersion() As String
            Get
                Return ResourceManager.GetString("Label_WithoutChangesSinceVersion", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
